[project]
name = "justpath"
version = "0.1.3"
description = "Explore PATH environment variable on Windows, Mac and Linux."
authors = [{ name = "Evgeny Pogrebnyak", email = "e.pogrebnyak@gmail.com" }]
license = "MIT"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "rich>=14.3.3",
    "typer>=0.24.1",
]

[project.urls]
repository = "https://github.com/epogrebnyak/justpath"

[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project.scripts]
justpath = "justpath.cli:typer_app"

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "pytest-cov>=4.0",
]

[tool.mypy]
ignore_missing_imports = true
